version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      aws-sdk-go:
        patterns:
          - "github.com/aws/aws-sdk-go*"
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
