name: Go
on: [push]
jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.20"
          - "1.21"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build & Test
        run: |
          make setup_ci
          make setup
          make test

      - name: build with version
        run: |
          git fetch --unshallow
          make
          version=$(./cmd/maprobe/maprobe version 2>&1)
          if [[ echo "$version" | grep -q "HEAD" ]]; then
            echo "failed to embedded version"
            exit 1
          else
            echo $version
          fi
